### ISSUE TITLE
broken links on the Creating an Auction page

### ISSUE THREAD

**Issue by randyhart** [18F/micropurchase-archive#1]
A few of the links are coming back as 404.  The `insights` page and `some past auctions` don't work in this paragraph.

`Before you get too far along, we recommend looking at our insights page and some past auctions to get a sense of what's worked well for recent customers. Once you're ready, read below to get started.`

Also - the `policies page` link in the last paragraph isn't working.  I couldn't figure out how to fix them for you.

**Comment by randyhart** [comment]
@stvnrlly

**Comment by stvnrlly** [comment]
Thanks, @randyhart! This should be fixed now, and I caught a few more while I was at it.
